# Generated by Django 5.1.2 on 2024-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_attempt', '0002_alter_todo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvbMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
