// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTask(arg1:number):Promise<void>;

export function Insert(arg1:main.todos):Promise<number>;

export function ListTodos():Promise<Array<main.todos>>;

export function ToggleStatus(arg1:number):Promise<void>;
