// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function Insert(arg1) {
  return window['go']['main']['App']['Insert'](arg1);
}

export function ListTodos() {
  return window['go']['main']['App']['ListTodos']();
}

export function ToggleStatus(arg1) {
  return window['go']['main']['App']['ToggleStatus'](arg1);
}
